pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo "Building project.."'
            }
        }
        
        stage('Test') {
            steps {
                sh 'echo "Running test"'
            }
        }

        stage('Deploy') {
            steps {
                sh 'echo "Deploying step"'
            }
        }
        
    }
}